version: '3'
services:
  postgres:
    image: postgres:10
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - pg-net
  redis:
    image: redis:5.0.4
    networks:
      - redis-net
  discourse_ruby_trunk:
    privileged: true
    build: .
    networks:
      - redis-net
      - pg-net
    depends_on:
      - postgres
      - redis
networks:
  redis-net:
  pg-net:
